version: "2"

run:
  timeout: 3m
  allow-parallel-runners: true
linters:
  default: fast
  disable:
    - depguard
    - lll
    - nlreturn
    - wsl
    - mnd
    - cyclop
    - funlen
    - gocognit
    - nestif
