services:
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/src

  db:
    image: mariadb:latest
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/mysql:/var/lib/mysql
    environment:
      MARIADB_DATABASE: $NS_MARIADB_DATABASE
      MARIADB_PORT: $NS_MARIADB_PORT
      MARIADB_USER: $NS_MARIADB_USER
      MARIADB_PASSWORD: $NS_MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD: qwerty
