name: backend CI

on:
  push:
    paths:
      - "backend/**"
      - "!backend/db/**"
      - ".github/workflows/backend.yml"
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  backend-lint:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: golang setup
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          working-directory: backend
          args: --config=backend/.golangci.yml

  backend-build:
    name: build backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: golang setup
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - name: go mod tidy
        run: go mod tidy
      - name: go build
        run: go build ./...
